### ISSUE TITLE
 ReflectionException

### ISSUE THREAD

**Issue by mutazhameed** [jeremykenedy/laravel-phpinfo#2]
hi Jeremy, i'm using your [laravel-auth](https://github.com/jeremykenedy/laravel-auth) thanks for that, but when i try to view PHPinfo i get
` ReflectionException (-1)
Class jeremykenedy\LaravelPhpInfo\App\Http\Controllers\LaravelPhpInfoController does not exist`

i looked into folder structure and app/Http/Controllers/LaravelPhpInfoServiceProvider.php wasn't there, tried my best and created the file manually but still the problem is there!
any help?

**Comment by jeremykenedy** [comment]
The autoloader is jammed up.

Clear the autoloader with `composer dump-autoload` then run `composer update`

**Comment by mutazhameed** [comment]
i did published assets and ran `composer dump-autoload` , removed the package and install it again, but still nothing seems to work! any thoughts on what else to do? am using Laravel 5.6

php artisan route:list
`  ReflectionException  : Class jeremykenedy\LaravelPhpInfo\App\Http\Controllers\LaravelPhpInfoController does not exist

  at /var/www/html/laravel-auth2/vendor/laravel/framework/src/Illuminate/Container/Container.php: 767
    763|         if ($concrete instanceof Closure) {
    764|             return $concrete($this, $this->getLastParameterOverride());
    765|         }
    766|
  > 767|         $reflector = new ReflectionClass($concrete);
    768|
    769|         // If the type is not instantiable, the developer is attempting to resolve
    770|         // an abstract type such as an Interface of Abstract Class and there is
    771|         // no binding registered for the abstractions so we need to bail out.

  Exception trace:

  1   ReflectionClass::__construct("jeremykenedy\LaravelPhpInfo\App\Http\Controllers\LaravelPhpInfoController")
      /var/www/html/laravel-auth2/vendor/laravel/framework/src/Illuminate/Container/Container.php : 767

  2   Illuminate\Container\Container::build("jeremykenedy\LaravelPhpInfo\App\Http\Controllers\LaravelPhpInfoController")
      /var/www/html/laravel-auth2/vendor/laravel/framework/src/Illuminate/Container/Container.php : 646

  Please use the argument -v to see more details.     `

**Comment by jeremykenedy** [comment]
make sure the bootstrap folder is writable with chmod. Its an issue with permission or the cache the autoloader builds.

You can try removing manually the files located in bootstrap.cache folder as well.

**Comment by mutazhameed** [comment]
i changed mod -R the project dir to 777 -it's testing env - cleared cache manually from bootstrap/cache .. but still!!

**Comment by mutazhameed** [comment]
i also ran `composer dump-autoload` and `composer update` after

**Comment by mutazhameed** [comment]
im thinking what would cause the `app\Http\Controllers\LaravelPhpInfoController.php` not being created at first place?

**Comment by jeremykenedy** [comment]
The controller file does not get copied.

Here is what happens when you publish:
https://github.com/jeremykenedy/laravel-phpinfo/blob/master/src/LaravelPhpInfoServiceProvider.php#L47
