### ISSUE TITLE
Symfony - Route [login] not defined.

### ISSUE THREAD

**Issue by aclimarin** [jeremykenedy/laravel-phpinfo#5]
I'm using laravel 7 and i follow all the steps. But i'm geting an error  "Route [login] not defined"

lluminate\Routing\UrlGenerator::route
C:\...\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php:420

Routing
Controller
jeremykenedy\LaravelPhpInfo\App\Http\Controllers\LaravelPhpInfoController@phpinfo
Route name
laravelPhpInfo::phpinfo
Route parameters
—
Middleware
web
auth

The controller "LaravelPhpInfoController" do not exists

**Comment by jeremykenedy** [comment]
You don’t have Laravel authentication scaffolding installed.
